export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header
      style={{
        backgroundColor: "lightblue",
        padding: "1rem"
      }}
      >
        <div>
          <h1>This is Customers Header</h1>
        </div>
      </header>
      {children}
      <footer
      style={{
        backgroundColor: "ghostwhite",
        padding: "1rem"
      }}
      >
        <h1>This is Customers Footer</h1>
      </footer>
      </body>
    </html>
  )
}
