import { Metadata } from "next"
import ErrorWrapper from "./error-wrapper"
import Link from "next/dist/client/link"


export const metadata: Metadata = {
  title:  {
    template: '%s - by Oshaman',  // %s will be replaced by the title  given in the page, if no title is given, then the default title will be used.
    default: 'Default Title if not provided',
    // absolute: "This is absolute title"  // This might be causing issues
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
          <header 
          style={{
            backgroundColor: "violet",
            padding: "1rem",
          }}>
          <div className="flex justify-between ">
            <Link href="/">Home</Link>
            <h1> This is Header</h1>
          </div>
          </header>

          <ErrorWrapper>
      {children}
          </ErrorWrapper>

          <footer style={{
            backgroundColor: "skyblue",
            padding: "1rem"
          }}>
            <h1>This a footer</h1>
          </footer>
      </body>
    </html>
  )
}
