export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        
        {children}
        <footer 
        style={{
          backgroundColor: "ghostwhite",
          padding: "1rem"
        }}
        >
        <h1>This is Auth Footer</h1>
        </footer>
        </body>
    </html>
  )
}
